### PR TITLE
Updates for Glass XE 16.11

### PR DESCRIPTION
**Pull request by Splaktar**
Add debug logging.
Upgrade to GDK API 19 rev 4.
Cleaned up gradle build and manifest a little.
Updated README with requirements to build and version of GDK included.

### CODE REVIEW

**Comment by DDRBoxman** [comment]
Mind removing the iml files? And squashing these commits?

**Comment by Splaktar** [comment]
I'd love to, but I'm not exactly sure about how to do that. I guess that I need to create a separate branch locally and merge the changes there?

**Comment by DDRBoxman** [comment]
This should take you through the process, shouldn't be too painful.
http://davidwalsh.name/squash-commits-git

**Comment by Splaktar** [comment]
I'm not able to squash the commits due to having already pushed them. I will create a new pull request with the .iml files removed.

**Pull request closed without merging**
